ALTER TABLE tenants ADD COLUMN IF NOT EXISTS digest_enabled BOOLEAN DEFAULT true;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS digest_day INTEGER DEFAULT 1
  CHECK (digest_day BETWEEN 0 AND 6);
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS digest_hour INTEGER DEFAULT 8
  CHECK (digest_hour BETWEEN 0 AND 23);
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS digest_last_sent_at TIMESTAMPTZ;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS timezone TEXT DEFAULT 'America/Chicago';
